/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Monitors */
        get: operations["list_monitors_api_monitors_get"];
        put?: never;
        /** Create Monitor */
        post: operations["create_monitor_api_monitors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitors/{monitor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Monitor */
        get: operations["read_monitor_api_monitors__monitor_id__get"];
        put?: never;
        post?: never;
        /** Delete Monitor */
        delete: operations["delete_monitor_api_monitors__monitor_id__delete"];
        options?: never;
        head?: never;
        /** Update Monitor */
        patch: operations["update_monitor_api_monitors__monitor_id__patch"];
        trace?: never;
    };
    "/api/monitors/{monitor_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Monitor Now
         * @description Run one cycle immediately.
         *
         *     Takes the same semaphore as the scheduler: a manual run must not double the
         *     request rate against the upstream. Notifications are wired in T4; this
         *     returns the counts so a user can tell whether a rule is configured sanely.
         */
        post: operations["run_monitor_now_api_monitors__monitor_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channels */
        get: operations["list_channels_api_channels_get"];
        put?: never;
        /** Create Channel */
        post: operations["create_channel_api_channels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Channel */
        delete: operations["delete_channel_api_channels__channel_id__delete"];
        options?: never;
        head?: never;
        /** Update Channel */
        patch: operations["update_channel_api_channels__channel_id__patch"];
        trace?: never;
    };
    "/api/channels/{channel_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Channel
         * @description Send a sample message through the real delivery path.
         *
         *     Deliberately the same `deliver()` used by the scheduler: a test that took a
         *     shortcut would pass while real notifications fail.
         */
        post: operations["test_channel_api_channels__channel_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notify-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notify Logs */
        get: operations["list_notify_logs_api_notify_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist */
        get: operations["list_watchlist_api_watchlist_get"];
        put?: never;
        /** Add To Watchlist */
        post: operations["add_to_watchlist_api_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Watchlist */
        delete: operations["remove_from_watchlist_api_watchlist__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Watchlist */
        patch: operations["update_watchlist_api_watchlist__item_id__patch"];
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Items
         * @description One row per ITEM, not per hit.
         *
         *     An item can match several rules; expanding by hit would list the same
         *     phone three times when the question being asked is "which items are
         *     there". Naming a monitor_id narrows the rows to that rule's matches and
         *     fills in the hit fields.
         */
        get: operations["list_items_api_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Item Prices
         * @description Ascending by time, because that is the axis a step chart draws against.
         *
         *     The newest `limit` points are taken and then reversed: capping an ascending
         *     query would return the OLDEST points and quietly plot a chart that stops
         *     before the present. The ordering is by `captured_at` and not by `id` --
         *     ordering a time series by insertion and trusting the two to agree plots a
         *     chart that never happened the first time they do not.
         */
        get: operations["item_prices_api_items__item_id__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Session
         * @description `needs_verification` is the difference between "wait" and "a human must
         *     act" — the UI has to be able to say which, or a challenged session looks
         *     identical to a quiet market.
         */
        get: operations["read_session_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/cookies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Cookies */
        post: operations["import_cookies_api_session_cookies_post"];
        /** Clear Cookies */
        delete: operations["clear_cookies_api_session_cookies_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Unauthenticated on purpose — it must work as a container healthcheck.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Cheapest possible way for the frontend to validate a stored token.
         */
        get: operations["whoami_api_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChannelCreate */
        ChannelCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "email" | "telegram";
            /** Label */
            label: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * ChannelPublic
         * @description Secrets are replaced with a presence marker before this leaves the app.
         *
         *     The page needs to know WHETHER a token is set, never what it is.
         */
        ChannelPublic: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChannelUpdate */
        ChannelUpdate: {
            /** Label */
            label?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * CookieImport
         * @description A paste from the browser's devtools.
         *
         *     A raw Cookie header rather than a structured list: that is the one form a
         *     user can actually produce without tooling, and asking for JSON would mean
         *     they hand-edit it and get it wrong.
         */
        CookieImport: {
            /** Cookie Header */
            cookie_header: string;
            /**
             * Origin
             * @default https://www.goofish.com
             */
            origin: string;
        };
        /**
         * CycleResult
         * @description Returned by run-now so the user sees what a rule actually does.
         */
        CycleResult: {
            /** Collected */
            collected: number;
            /** Passed */
            passed: number;
            /** Notifiable */
            notifiable: number;
            /** Collector */
            collector?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Baseline
             * @default false
             */
            baseline: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemPublic
         * @description One collected listing, shared by the list and the detail endpoint.
         *
         *     Seller fields are all optional and mean "not fetched", NOT zero. In this
         *     product 0 reviews is a danger signal and unknown is merely missing data;
         *     collapsing them would turn "we could not check" into "we checked and it is
         *     bad".
         *
         *     Hit fields are populated only when the request named a monitor_id, because
         *     `unverified_filters` is a property of one rule's match, not of the item.
         */
        ItemPublic: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Cover Url */
            cover_url: string | null;
            /** Image Urls */
            image_urls: string[];
            /** Region */
            region: string | null;
            /** Status */
            status: string;
            /** Price Cents */
            price_cents: number;
            /** Publish Time */
            publish_time: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Seller Id */
            seller_id: string;
            /** Seller Nick */
            seller_nick: string;
            /** Seller Avatar Url */
            seller_avatar_url: string | null;
            /** Seller Is Shop */
            seller_is_shop: boolean | null;
            /** Seller Credit Level */
            seller_credit_level: number | null;
            /** Seller Credit Score */
            seller_credit_score: number | null;
            /** Seller Review Count */
            seller_review_count: number | null;
            /** Seller Positive Rate */
            seller_positive_rate: number | null;
            /** Seller Sold Count */
            seller_sold_count: number | null;
            /** Seller Verified */
            seller_verified: boolean | null;
            /** First Hit At */
            first_hit_at?: string | null;
            /** Notified At */
            notified_at?: string | null;
            /** In Range */
            in_range?: boolean | null;
            /** Unverified Filters */
            unverified_filters?: string[] | null;
        };
        /** MonitorCreate */
        MonitorCreate: {
            /** Name */
            name: string;
            /** Keyword */
            keyword: string;
            /**
             * Exclude Words
             * @default
             */
            exclude_words: string;
            /** Price Min Cents */
            price_min_cents?: number | null;
            /** Price Max Cents */
            price_max_cents?: number | null;
            /** Published Within Hours */
            published_within_hours?: number | null;
            /** Region */
            region?: string | null;
            /** Condition */
            condition?: string | null;
            /** Free Shipping */
            free_shipping?: boolean | null;
            /** Min Seller Credit */
            min_seller_credit?: number | null;
            /**
             * Exclude Shop
             * @default false
             */
            exclude_shop: boolean;
            /**
             * Interval Seconds
             * @default 300
             */
            interval_seconds: number;
            /**
             * Channel Ids
             * @default []
             */
            channel_ids: number[];
        };
        /**
         * MonitorPublic
         * @description What the management page renders.
         *
         *     The health fields are not decoration: a monitoring tool whose failures are
         *     invisible is worse than one that stopped. See design.md section 12.
         */
        MonitorPublic: {
            /** Name */
            name: string;
            /** Keyword */
            keyword: string;
            /**
             * Exclude Words
             * @default
             */
            exclude_words: string;
            /** Price Min Cents */
            price_min_cents?: number | null;
            /** Price Max Cents */
            price_max_cents?: number | null;
            /** Published Within Hours */
            published_within_hours?: number | null;
            /** Region */
            region?: string | null;
            /** Condition */
            condition?: string | null;
            /** Free Shipping */
            free_shipping?: boolean | null;
            /** Min Seller Credit */
            min_seller_credit?: number | null;
            /**
             * Exclude Shop
             * @default false
             */
            exclude_shop: boolean;
            /**
             * Interval Seconds
             * @default 300
             */
            interval_seconds: number;
            /** Id */
            id: number;
            /** Enabled */
            enabled: boolean;
            /** Baseline Done */
            baseline_done: boolean;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Last Collector */
            last_collector: string | null;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Hit Count */
            hit_count: number;
            /**
             * Channel Ids
             * @default []
             */
            channel_ids: number[];
        };
        /**
         * MonitorUpdate
         * @description Every field optional: PATCH semantics. Validation of the ones that are
         *     present still applies.
         */
        MonitorUpdate: {
            /** Name */
            name?: string | null;
            /** Keyword */
            keyword?: string | null;
            /** Exclude Words */
            exclude_words?: string | null;
            /** Price Min Cents */
            price_min_cents?: number | null;
            /** Price Max Cents */
            price_max_cents?: number | null;
            /** Published Within Hours */
            published_within_hours?: number | null;
            /** Region */
            region?: string | null;
            /** Condition */
            condition?: string | null;
            /** Free Shipping */
            free_shipping?: boolean | null;
            /** Min Seller Credit */
            min_seller_credit?: number | null;
            /** Exclude Shop */
            exclude_shop?: boolean | null;
            /** Interval Seconds */
            interval_seconds?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Channel Ids */
            channel_ids?: number[] | null;
        };
        /** NotifyLogPublic */
        NotifyLogPublic: {
            /** Id */
            id: number;
            /** Channel Id */
            channel_id: number;
            /** Kind */
            kind: string;
            /** Monitor Id */
            monitor_id: number | null;
            /** Item Count */
            item_count: number;
            /** Ok */
            ok: boolean;
            /** Error */
            error: string | null;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
        };
        /**
         * PricePoint
         * @description One observation. The series is ascending by time so a step chart can
         *     draw it directly: the price held until the next point, which is why the
         *     chart is a step line and never a smoothed curve.
         */
        PricePoint: {
            /** Price Cents */
            price_cents: number;
            /** Status */
            status: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Source */
            source: string;
            /** Want Count */
            want_count: number | null;
            /** View Count */
            view_count: number | null;
        };
        /**
         * SessionState
         * @description Session health. Carries cookie NAMES and never values.
         */
        SessionState: {
            /** Origin */
            origin: string | null;
            /** Usable */
            usable: boolean;
            /** Needs Verification */
            needs_verification: boolean;
            /** Established At */
            established_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Challenged Apis */
            challenged_apis: string[];
            /** Cookie Names */
            cookie_names: string[];
        };
        /** TestSendResult */
        TestSendResult: {
            /** Ok */
            ok: boolean;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WatchlistCreate
         * @description Two ways in: an item already in the database, or a pasted link.
         *
         *     The link path matters — without it the tool is closed inside its own search
         *     results, and the specific thing the user actually wants to buy (spotted in
         *     the app, or sent by a friend) cannot be watched at all.
         */
        WatchlistCreate: {
            /** Item Id */
            item_id?: string | null;
            /** Url */
            url?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Interval Seconds
             * @default 300
             */
            interval_seconds: number;
        };
        /** WatchlistPublic */
        WatchlistPublic: {
            /** Item Id */
            item_id: string;
            /** Title */
            title: string;
            /** Price Cents */
            price_cents: number;
            /** Added Price Cents */
            added_price_cents: number;
            /** Change Cents */
            change_cents: number;
            /** Change Ratio */
            change_ratio: number;
            /** Status */
            status: string;
            /** Cover Url */
            cover_url: string | null;
            /** Seller Nick */
            seller_nick: string;
            /** Seller Is Shop */
            seller_is_shop: boolean | null;
            /** Seller Credit Level */
            seller_credit_level: number | null;
            /** Seller Positive Rate */
            seller_positive_rate: number | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Listed Days */
            listed_days: number;
            /** Note */
            note: string | null;
            /** Price Watch Enabled */
            price_watch_enabled: boolean;
            /** Interval Seconds */
            interval_seconds: number;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Error */
            last_error: string | null;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /** WatchlistUpdate */
        WatchlistUpdate: {
            /** Note */
            note?: string | null;
            /** Price Watch Enabled */
            price_watch_enabled?: boolean | null;
            /** Interval Seconds */
            interval_seconds?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_monitors_api_monitors_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_monitor_api_monitors_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_monitor_api_monitors__monitor_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                monitor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_monitor_api_monitors__monitor_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                monitor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_monitor_api_monitors__monitor_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                monitor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_monitor_now_api_monitors__monitor_id__run_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                monitor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channels_api_channels_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_channel_api_channels_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_channel_api_channels__channel_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_channel_api_channels__channel_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_channel_api_channels__channel_id__test_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestSendResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notify_logs_api_notify_logs_get: {
        parameters: {
            query?: {
                limit?: number;
                channel_id?: number | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifyLogPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_api_watchlist_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_watchlist_api_watchlist_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_api_watchlist__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watchlist_api_watchlist__item_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_items_get: {
        parameters: {
            query?: {
                monitor_id?: number | null;
                min_price_cents?: number | null;
                max_price_cents?: number | null;
                status?: ("on_sale" | "sold" | "removed") | null;
                sort?: "-first_seen" | "first_seen" | "-last_seen" | "price" | "-price";
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_items__item_id__get: {
        parameters: {
            query?: {
                monitor_id?: number | null;
            };
            header?: {
                authorization?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_prices_api_items__item_id__prices_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_session_api_session_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_cookies_api_session_cookies_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CookieImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cookies_api_session_cookies_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    whoami_api_whoami_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
