/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Monitors */
        get: operations["list_monitors_api_monitors_get"];
        put?: never;
        /** Create Monitor */
        post: operations["create_monitor_api_monitors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitors/{monitor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Monitor */
        get: operations["read_monitor_api_monitors__monitor_id__get"];
        put?: never;
        post?: never;
        /** Delete Monitor */
        delete: operations["delete_monitor_api_monitors__monitor_id__delete"];
        options?: never;
        head?: never;
        /** Update Monitor */
        patch: operations["update_monitor_api_monitors__monitor_id__patch"];
        trace?: never;
    };
    "/api/monitors/{monitor_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Monitor Now
         * @description Run one cycle immediately.
         *
         *     Takes the same semaphore as the scheduler: a manual run must not double the
         *     request rate against the upstream. Notifications are wired in T4; this
         *     returns the counts so a user can tell whether a rule is configured sanely.
         */
        post: operations["run_monitor_now_api_monitors__monitor_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channels */
        get: operations["list_channels_api_channels_get"];
        put?: never;
        /** Create Channel */
        post: operations["create_channel_api_channels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Channel */
        delete: operations["delete_channel_api_channels__channel_id__delete"];
        options?: never;
        head?: never;
        /** Update Channel */
        patch: operations["update_channel_api_channels__channel_id__patch"];
        trace?: never;
    };
    "/api/channels/{channel_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Channel
         * @description Send a sample message through the real delivery path.
         *
         *     Deliberately the same `deliver()` used by the scheduler: a test that took a
         *     shortcut would pass while real notifications fail.
         */
        post: operations["test_channel_api_channels__channel_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notify-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notify Logs */
        get: operations["list_notify_logs_api_notify_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist */
        get: operations["list_watchlist_api_watchlist_get"];
        put?: never;
        /** Add To Watchlist */
        post: operations["add_to_watchlist_api_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Watchlist */
        delete: operations["remove_from_watchlist_api_watchlist__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Watchlist */
        patch: operations["update_watchlist_api_watchlist__item_id__patch"];
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Items
         * @description One row per ITEM, not per hit.
         *
         *     An item can match several rules; expanding by hit would list the same
         *     phone three times when the question being asked is "which items are
         *     there". Naming a monitor_id narrows the rows to that rule's matches and
         *     fills in the hit fields.
         */
        get: operations["list_items_api_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Item Prices
         * @description Ascending by time, because that is the axis a step chart draws against.
         *
         *     The newest `limit` points are taken and then reversed: capping an ascending
         *     query would return the OLDEST points and quietly plot a chart that stops
         *     before the present. The ordering is by `captured_at` and not by `id` --
         *     ordering a time series by insertion and trusting the two to agree plots a
         *     chart that never happened the first time they do not.
         */
        get: operations["item_prices_api_items__item_id__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Session
         * @description `needs_verification` is the difference between "wait" and "a human must
         *     act" — the UI has to be able to say which, or a challenged session looks
         *     identical to a quiet market.
         */
        get: operations["read_session_api_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/cookies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Cookies */
        post: operations["import_cookies_api_session_cookies_post"];
        /** Clear Cookies */
        delete: operations["clear_cookies_api_session_cookies_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/price-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Price Distribution
         * @description Where this keyword's asking prices sit, one sample per listing.
         *
         *     `days` bounds which listings count: those seen at least once in the
         *     window. The default is a week rather than "only what is on sale right
         *     now" because a cycle reads the first 30 search results, so the live set is
         *     about 30 listings per keyword — enough to draw, not enough to trust.
         *     `fresh_size` is what says how much of the window is still live.
         */
        get: operations["price_distribution_api_analytics_price_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/price-drops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Price Drops
         * @description Listings that have come down over the window, deepest first.
         *
         *     Here `days` sets what "before" means: the price at the start of the
         *     window, compared with the current one. A listing that first appeared
         *     inside the window has no earlier price and is excluded.
         */
        get: operations["price_drops_api_analytics_price_drops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/supply-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Supply Trend
         * @description New listings per day, with days we did not collect marked as such.
         *
         *     Here `days` is simply the width of the chart. Every day in the window is
         *     present, including ones with no records at all — a gap in the series would
         *     let the frontend close it up and invent a trend.
         */
        get: operations["supply_trend_api_analytics_supply_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/listing-duration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listing Duration
         * @description How long this keyword's listings stayed inside our observation range.
         *
         *     Here `days` bounds which listings count by their FIRST sighting, so the
         *     distribution cannot be stretched by listings older than the history it
         *     claims to cover. Only listings that have gone stale are in it — a listing
         *     still coming back has no duration yet, only an age.
         *
         *     Read `aperture_pages_min` / `aperture_pages_max` before reading the
         *     numbers. They are the page counts the cycles behind this window actually
         *     fetched, and when they differ the observation range changed mid-window,
         *     which makes the distribution incomparable with itself.
         */
        get: operations["listing_duration_api_analytics_listing_duration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Endpoints
         * @description One query regardless of how many endpoints exist.
         *
         *     `api_key_configured` is derived from the row that is already loaded, so
         *     there is nothing here to turn into a per-row lookup — pinned by a test
         *     that compares query counts at 3 and 30 rows for equality.
         *
         *     ponytail: no `limit`, like `/api/channels`. These rows are typed in by
         *     hand, one per gateway; add paging when someone has 200 of them.
         */
        get: operations["list_endpoints_api_llm_endpoints_get"];
        put?: never;
        /** Create Endpoint */
        post: operations["create_endpoint_api_llm_endpoints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/endpoints/{endpoint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Endpoint
         * @description Detaches the scenarios that pointed here, and disables them.
         *
         *     Leaving `endpoint_id` dangling would make the analyze routes fail with
         *     whatever a missing row turns into, one layer away from the cause. A
         *     scenario with no endpoint cannot run at all, so it goes back to disabled
         *     rather than staying green in the UI.
         */
        delete: operations["delete_endpoint_api_llm_endpoints__endpoint_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Endpoint
         * @description An omitted `api_key` keeps the stored one; `""` clears it.
         *
         *     No "was this the redacted placeholder" check is needed, unlike
         *     `channels.py`: nothing ever handed the page a value to send back.
         */
        patch: operations["update_endpoint_api_llm_endpoints__endpoint_id__patch"];
        trace?: never;
    };
    "/api/llm/endpoints/{endpoint_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Endpoint Models
         * @description Available models, or an empty list and a reason — always HTTP 200.
         *
         *     A deliberate exception to `error-handling.md`'s "errors use status codes":
         *     a gateway that does not implement the models route is not an error, it is
         *     the common case (the probed DeepSeek endpoint does implement it, which is
         *     why the happy path is testable at all). The user's next action either way
         *     is to type the model name, and a 4xx here would read as "your endpoint is
         *     broken" and stop them. `discover_models` never raises for that reason.
         *
         *     The 404 below is a different thing: that is OUR row missing, not theirs.
         */
        get: operations["list_endpoint_models_api_llm_endpoints__endpoint_id__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/endpoints/{endpoint_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Endpoint
         * @description One real completion, so "test connection" tests the connection.
         *
         *     Three distinct not-ok outcomes, because they have three different fixes:
         *     the endpoint refused us (check base_url / key / model id), the model spent
         *     the whole budget thinking (raise max_tokens), or nothing came back at all.
         *     Collapsing them is the misdirected error `error-handling.md` forbids.
         */
        post: operations["test_endpoint_api_llm_endpoints__endpoint_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/scenarios/{scenario}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Scenario
         * @description No stored row is the state every install starts in, not a 404.
         *
         *     The config page needs a shape to render before anything has been saved,
         *     and the defaults it should render are exactly the model's own.
         */
        get: operations["read_scenario_api_llm_scenarios__scenario__get"];
        /**
         * Save Scenario
         * @description Upsert. PUT rather than PATCH: there is one row per scenario and the
         *     page owns the whole form, so a partial update has no meaning here.
         *
         *     The template is stored as given. Placeholders are not validated — see
         *     `LlmScenarioUpdate` for why an unknown one is left alone on purpose.
         */
        put: operations["save_scenario_api_llm_scenarios__scenario__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/scenarios/{scenario}/default-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Default Prompt
         * @description The built-in template plus the placeholder contract.
         *
         *     Both in one response because the page needs both at once: "restore
         *     default" writes the template, and the list beside the editor is the only
         *     place a user can learn what `{stats}` is allowed to be.
         */
        get: operations["read_default_prompt_api_llm_scenarios__scenario__default_prompt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/analyze/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Market
         * @description One market reading for one keyword, from the aggregated statistics.
         *
         *     **User-triggered only.** Nothing schedules this, nothing warms the cache,
         *     and the collection loop cannot reach it: a rule polls every 300 s, so an
         *     LLM call wired into the cycle is per-minute billing (prd.md risk table).
         *     POST rather than GET for the same reason — it spends money, and a GET is
         *     something a browser or a link preview will fetch on its own.
         *
         *     A repeat click inside the same window is free: the cache key is a digest
         *     of the prompt, so it hits until the statistics behind it actually move
         *     (`market.market_cache_key`).
         */
        post: operations["analyze_market_api_llm_analyze_market_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/analyze/item/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Item
         * @description One listing, read against the market of one keyword. Never cached.
         *
         *     Never cached, unlike `market`: the price and the seller's state are the
         *     two things this answer turns on, and a stored verdict on a listing that
         *     has since dropped 800 yuan is worse than no verdict. There is nothing to
         *     invalidate it either — a price change writes a snapshot, not an event.
         *
         *     Only ever reached by a user pressing the button (FR-P4-4). Nothing
         *     schedules it; a per-cycle version of this route would bill per minute.
         *
         *     The five inputs are assembled by `llm/items.py` and every one of them
         *     degrades to a sentence rather than to silence, so `notes` is part of the
         *     answer: a verdict written without the photos must not look like one
         *     written with them.
         */
        post: operations["analyze_item_api_llm_analyze_item__item_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Unauthenticated on purpose — it must work as a container healthcheck.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Cheapest possible way for the frontend to validate a stored token.
         */
        get: operations["whoami_api_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChannelCreate */
        ChannelCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "email" | "telegram";
            /** Label */
            label: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * ChannelPublic
         * @description Secrets are replaced with a presence marker before this leaves the app.
         *
         *     The page needs to know WHETHER a token is set, never what it is.
         */
        ChannelPublic: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChannelUpdate */
        ChannelUpdate: {
            /** Label */
            label?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * CookieImport
         * @description A paste from the browser's devtools.
         *
         *     A raw Cookie header rather than a structured list: that is the one form a
         *     user can actually produce without tooling, and asking for JSON would mean
         *     they hand-edit it and get it wrong.
         */
        CookieImport: {
            /** Cookie Header */
            cookie_header: string;
            /**
             * Origin
             * @default https://www.goofish.com
             */
            origin: string;
        };
        /**
         * CycleResult
         * @description Returned by run-now so the user sees what a rule actually does.
         */
        CycleResult: {
            /** Collected */
            collected: number;
            /** Passed */
            passed: number;
            /** Notifiable */
            notifiable: number;
            /** Collector */
            collector?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Baseline
             * @default false
             */
            baseline: boolean;
        };
        /**
         * DurationBucket
         * @description One histogram column, in minutes, on readable step boundaries.
         *
         *     The step adapts to the spread (`analytics.duration_align`): 5, 10, 15, 30
         *     minutes, then hours. Hour-aligned edges were the original plan and they
         *     collapsed the real data into two bars, because the median listing stays in
         *     range for 1 to 9 minutes.
         */
        DurationBucket: {
            /** Lo Minutes */
            lo_minutes: number;
            /** Hi Minutes */
            hi_minutes: number;
            /** Count */
            count: number;
        };
        /**
         * DurationQuantiles
         * @description Minutes. Empty below two samples, for the same reason PriceQuantiles is.
         */
        DurationQuantiles: {
            /** P10 */
            p10?: number | null;
            /** P25 */
            p25?: number | null;
            /** P50 */
            p50?: number | null;
            /** P75 */
            p75?: number | null;
            /** P90 */
            p90?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemPublic
         * @description One collected listing, shared by the list and the detail endpoint.
         *
         *     Seller fields are all optional and mean "not fetched", NOT zero. In this
         *     product 0 reviews is a danger signal and unknown is merely missing data;
         *     collapsing them would turn "we could not check" into "we checked and it is
         *     bad".
         *
         *     Hit fields are populated only when the request named a monitor_id, because
         *     `unverified_filters` is a property of one rule's match, not of the item.
         */
        ItemPublic: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Cover Url */
            cover_url: string | null;
            /** Image Urls */
            image_urls: string[];
            /** Region */
            region: string | null;
            /** Status */
            status: string;
            /** Price Cents */
            price_cents: number;
            /** Publish Time */
            publish_time: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Seller Id */
            seller_id: string;
            /** Seller Nick */
            seller_nick: string;
            /** Seller Avatar Url */
            seller_avatar_url: string | null;
            /** Seller Is Shop */
            seller_is_shop: boolean | null;
            /** Seller Credit Level */
            seller_credit_level: number | null;
            /** Seller Credit Score */
            seller_credit_score: number | null;
            /** Seller Review Count */
            seller_review_count: number | null;
            /** Seller Positive Rate */
            seller_positive_rate: number | null;
            /** Seller Sold Count */
            seller_sold_count: number | null;
            /** Seller Verified */
            seller_verified: boolean | null;
            /** First Hit At */
            first_hit_at?: string | null;
            /** Notified At */
            notified_at?: string | null;
            /** In Range */
            in_range?: boolean | null;
            /** Unverified Filters */
            unverified_filters?: string[] | null;
        };
        /**
         * ListingDuration
         * @description How long listings stayed inside our observation range.
         *
         *     Not a time to sale, and the field names must never start claiming it is: a
         *     listing stops coming back because it was bought, because it was delisted,
         *     or because its rank fell past the pages we read — and the last of those is
         *     our own doing.
         *
         *     Which is why the aperture is part of the response and not a footnote.
         *     `aperture_pages_min` / `max` are the narrowest and widest page counts any
         *     cycle for this keyword actually fetched inside the window, with rows
         *     written before paging existed counted as the single page they were.
         *     **When the two differ, the aperture changed mid-window and the
         *     distribution is not internally comparable** — a wider aperture makes a
         *     listing "leave" later, so the shape is partly a measurement of us. Both
         *     are null when no cycle in the window recorded an aperture, which is not
         *     the same as one page.
         *
         *     Durations are integer minutes for the same reason prices are integer
         *     cents. Histogram edges land on a readable step chosen from the spread,
         *     not on a fixed hour: at this poll interval most durations are minutes, and
         *     hour buckets showed 264 samples as a single bar.
         */
        ListingDuration: {
            /** Sample Size */
            sample_size: number;
            /** Data Days */
            data_days: number;
            /** Window Days */
            window_days: number;
            quantiles: components["schemas"]["DurationQuantiles"];
            /** Histogram */
            histogram: components["schemas"]["DurationBucket"][];
            /** Aperture Pages Min */
            aperture_pages_min?: number | null;
            /** Aperture Pages Max */
            aperture_pages_max?: number | null;
            /** Aperture Rows */
            aperture_rows: number;
            /**
             * Legacy Clock Rows
             * @default 0
             */
            legacy_clock_rows: number;
        };
        /**
         * LlmDefaultPrompt
         * @description The built-in template plus the placeholders it is allowed to use.
         */
        LlmDefaultPrompt: {
            /** Scenario */
            scenario: string;
            /** Prompt Template */
            prompt_template: string;
            /** Placeholders */
            placeholders: string[];
        };
        /**
         * LlmEndpointCreate
         * @description `api_key` is accepted here and appears on NO response model.
         *
         *     Not even masked, not even as a length. The channel pages redact a stored
         *     secret on the way out and then have to defend against the redacted value
         *     being PATCHed back over the real one (`api/channels.py`); a key that is
         *     never echoed has no such round trip to get wrong.
         *
         *     Empty is allowed: a local Ollama or a self-hosted vLLM needs no key, and
         *     demanding a placeholder there would teach users to type one.
         */
        LlmEndpointCreate: {
            /** Label */
            label: string;
            /** Base Url */
            base_url: string;
            /**
             * Api Key
             * @default
             */
            api_key: string;
            /**
             * Wire Format
             * @default openai
             * @enum {string}
             */
            wire_format: "openai" | "anthropic";
        };
        /**
         * LlmEndpointPublic
         * @description `api_key_configured` is the entire answer the page gets about the key.
         */
        LlmEndpointPublic: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Base Url */
            base_url: string;
            /** Wire Format */
            wire_format: string;
            /** Api Key Configured */
            api_key_configured: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * LlmEndpointUpdate
         * @description Absent `api_key` leaves the stored one alone; `""` clears it.
         *
         *     The distinction is why this is `str | None` and not `str`: the config page
         *     submits the form without a key whenever the user did not retype it.
         */
        LlmEndpointUpdate: {
            /** Label */
            label?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Wire Format */
            wire_format?: ("openai" | "anthropic") | null;
        };
        /**
         * LlmItemAnalysis
         * @description One single-item advice call, in the four states the panel renders.
         *
         *     `kind` carries `LlmOutcome`'s four values unchanged rather than collapsing
         *     them into ok/error: `starved` is fixed by raising max_tokens, `empty` by
         *     checking the model id, and `unparsable` by fixing the template — and
         *     `unparsable` is the one that must still show `text`, because a user
         *     breaking their own prompt is a normal event with the model's own words as
         *     the only useful thing to look at.
         *
         *     `keyword` is which market the listing was compared against, echoed because
         *     the choice is not obvious: an item can sit in two keywords' ledgers at
         *     different price levels and this one is "the rule that saw it first"
         *     (design §5). Null means it is in no ledger at all, and the advice was
         *     written without any market statistics.
         *
         *     `notes` are the inputs that did NOT make it in — a photo the CDN answered
         *     with a 1x1 pixel, an oversized one, a text-only degradation. An answer
         *     that silently dropped the pictures is indistinguishable from one that read
         *     them, which is why this is a field and not a log line.
         */
        LlmItemAnalysis: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "ok" | "starved" | "empty" | "unparsable";
            /** Text */
            text: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Calls
             * @default 1
             */
            calls: number;
            /** Message */
            message?: string | null;
            /** Keyword */
            keyword?: string | null;
            /** Notes */
            notes: string[];
            /** Images Sent */
            images_sent: number;
            /** Disclaimer */
            disclaimer: string;
        };
        /**
         * LlmMarketAnalysis
         * @description One market reading, in the four states the UI has to render.
         *
         *     `kind` carries the three HTTP-200 failure modes of design.md §4 apart, and
         *     they are NOT interchangeable: `starved` is fixed by raising max_tokens and
         *     `unparsable` by fixing the template, so collapsing them tells one of the
         *     two users to go and edit the thing that was never wrong. `text` is the
         *     model's own output, kept so the `unparsable` state can show it verbatim.
         *
         *     `no_data` is this layer's own fifth state: the keyword had no priced
         *     listing in the window, so no call was made at all. A billed call whose
         *     honest answer is "there is nothing here" is a call worth not making.
         *
         *     `reading` is a validated `app.llm.market.MarketReading` as a dict.
         *     Typed as `dict` on purpose — the JSON field names are already stated twice
         *     (in `prompts.MARKET_PROMPT` and in that model) and a third copy here would
         *     be a third place to drift, while the frontend types are hand-written in
         *     `web/src/api/types.ts` either way. `test_llm_market.py` pins the two that
         *     do exist against each other.
         *
         *     `disclaimer` has no default: it is required by FR-P4-3 and a default is a
         *     thing a later route can quietly stop passing.
         */
        LlmMarketAnalysis: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "ok" | "starved" | "empty" | "unparsable" | "no_data";
            /** Keyword */
            keyword: string;
            /** Window Days */
            window_days: number;
            /** Data Days */
            data_days: number;
            /** Sample Size */
            sample_size: number;
            /** Disclaimer */
            disclaimer: string;
            /** Reading */
            reading?: {
                [key: string]: unknown;
            } | null;
            /**
             * Text
             * @default
             */
            text: string;
            /** Message */
            message?: string | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /**
             * Calls
             * @default 0
             */
            calls: number;
        };
        /**
         * LlmMarketAnalyze
         * @description What the market panel asks for: a keyword and the window it is showing.
         *
         *     `days` bounds all four metrics at once, unlike the analytics routes where
         *     it means something different in each. The prompt says "最近 N 天" over a
         *     single block of numbers, and mixing windows inside it would be a lie to
         *     the model about figures it has no way to check. Default 30 matches the
         *     analytics page's window selector, which is where the button lives.
         */
        LlmMarketAnalyze: {
            /** Keyword */
            keyword: string;
            /**
             * Days
             * @default 30
             */
            days: number;
        };
        /**
         * LlmModelList
         * @description An empty list plus a reason is a NORMAL answer, not a failure.
         *
         *     Plenty of relay gateways never implement the models route, so the useful
         *     response to a failed lookup is one the page can render beside a text input
         *     for typing the model name — a 4xx would read as "this endpoint is broken"
         *     and stop a user whose endpoint works fine.
         */
        LlmModelList: {
            /** Models */
            models: string[];
            /** Error */
            error?: string | null;
        };
        /**
         * LlmScenarioPublic
         * @description `prompt_template` null means the built-in default is in use.
         */
        LlmScenarioPublic: {
            /** Scenario */
            scenario: string;
            /** Endpoint Id */
            endpoint_id: number | null;
            /** Model */
            model: string | null;
            /** Prompt Template */
            prompt_template: string | null;
            /** Send Images */
            send_images: boolean;
            /** Max Tokens */
            max_tokens?: number | null;
            /**
             * Missing Placeholders
             * @default []
             */
            missing_placeholders: string[];
            /** Enabled */
            enabled: boolean;
        };
        /**
         * LlmScenarioUpdate
         * @description The whole scenario config, PUT as one object.
         *
         *     `prompt_template` is free text and is NOT checked against the placeholder
         *     contract. `prompts.render` substitutes with `str.replace`, so an unknown
         *     or typo'd `{plcaeholder}` survives into the prompt as visible text by
         *     design — the model sees a stray brace pair and the answer degrades, which
         *     is a far better failure than a 422 on a field a user is mid-edit in. The
         *     contract is published by `GET /scenarios/{scenario}/default-prompt` so the
         *     page can list it and offer the default back.
         */
        LlmScenarioUpdate: {
            /** Endpoint Id */
            endpoint_id?: number | null;
            /** Model */
            model?: string | null;
            /** Prompt Template */
            prompt_template?: string | null;
            /**
             * Send Images
             * @default false
             */
            send_images: boolean;
            /** Max Tokens */
            max_tokens?: number | null;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
        };
        /**
         * LlmTestResult
         * @description `text` is the model's own answer, which is what makes the button mean
         *     something: a reachable endpoint that returns nothing visible is a distinct
         *     outcome and it comes back as `ok: false` with its own message.
         */
        LlmTestResult: {
            /** Ok */
            ok: boolean;
            /** Error */
            error?: string | null;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** MonitorCreate */
        MonitorCreate: {
            /** Name */
            name: string;
            /** Keyword */
            keyword: string;
            /**
             * Exclude Words
             * @default
             */
            exclude_words: string;
            /** Price Min Cents */
            price_min_cents?: number | null;
            /** Price Max Cents */
            price_max_cents?: number | null;
            /** Published Within Hours */
            published_within_hours?: number | null;
            /** Region */
            region?: string | null;
            /** Condition */
            condition?: string | null;
            /** Free Shipping */
            free_shipping?: boolean | null;
            /** Min Seller Credit */
            min_seller_credit?: number | null;
            /**
             * Exclude Shop
             * @default false
             */
            exclude_shop: boolean;
            /**
             * Interval Seconds
             * @default 300
             */
            interval_seconds: number;
            /**
             * Channel Ids
             * @default []
             */
            channel_ids: number[];
        };
        /**
         * MonitorPublic
         * @description What the management page renders.
         *
         *     The health fields are not decoration: a monitoring tool whose failures are
         *     invisible is worse than one that stopped. See design.md section 12.
         */
        MonitorPublic: {
            /** Name */
            name: string;
            /** Keyword */
            keyword: string;
            /**
             * Exclude Words
             * @default
             */
            exclude_words: string;
            /** Price Min Cents */
            price_min_cents?: number | null;
            /** Price Max Cents */
            price_max_cents?: number | null;
            /** Published Within Hours */
            published_within_hours?: number | null;
            /** Region */
            region?: string | null;
            /** Condition */
            condition?: string | null;
            /** Free Shipping */
            free_shipping?: boolean | null;
            /** Min Seller Credit */
            min_seller_credit?: number | null;
            /**
             * Exclude Shop
             * @default false
             */
            exclude_shop: boolean;
            /**
             * Interval Seconds
             * @default 300
             */
            interval_seconds: number;
            /** Id */
            id: number;
            /** Enabled */
            enabled: boolean;
            /** Baseline Done */
            baseline_done: boolean;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Last Collector */
            last_collector: string | null;
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Hit Count */
            hit_count: number;
            /**
             * Channel Ids
             * @default []
             */
            channel_ids: number[];
        };
        /**
         * MonitorUpdate
         * @description Every field optional: PATCH semantics. Validation of the ones that are
         *     present still applies.
         */
        MonitorUpdate: {
            /** Name */
            name?: string | null;
            /** Keyword */
            keyword?: string | null;
            /** Exclude Words */
            exclude_words?: string | null;
            /** Price Min Cents */
            price_min_cents?: number | null;
            /** Price Max Cents */
            price_max_cents?: number | null;
            /** Published Within Hours */
            published_within_hours?: number | null;
            /** Region */
            region?: string | null;
            /** Condition */
            condition?: string | null;
            /** Free Shipping */
            free_shipping?: boolean | null;
            /** Min Seller Credit */
            min_seller_credit?: number | null;
            /** Exclude Shop */
            exclude_shop?: boolean | null;
            /** Interval Seconds */
            interval_seconds?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Channel Ids */
            channel_ids?: number[] | null;
        };
        /** NotifyLogPublic */
        NotifyLogPublic: {
            /** Id */
            id: number;
            /** Channel Id */
            channel_id: number;
            /** Kind */
            kind: string;
            /** Monitor Id */
            monitor_id: number | null;
            /** Item Count */
            item_count: number;
            /** Ok */
            ok: boolean;
            /** Error */
            error: string | null;
            /**
             * Sent At
             * Format: date-time
             */
            sent_at: string;
        };
        /**
         * PriceBucket
         * @description One histogram column. Edges are whole yuan in cents.
         */
        PriceBucket: {
            /** Lo Cents */
            lo_cents: number;
            /** Hi Cents */
            hi_cents: number;
            /** Count */
            count: number;
        };
        /**
         * PriceDistribution
         * @description `fresh_size` is separate from `sample_size` on purpose: the first says
         *     how much the distribution covers, the second how much of it is still on
         *     sale right now. With only the first, four-day-old asking prices read as
         *     the current market.
         */
        PriceDistribution: {
            /** Sample Size */
            sample_size: number;
            /** Data Days */
            data_days: number;
            /** Window Days */
            window_days: number;
            quantiles: components["schemas"]["PriceQuantiles"];
            /** Histogram */
            histogram: components["schemas"]["PriceBucket"][];
            /** Fresh Size */
            fresh_size: number;
        };
        /**
         * PriceDrop
         * @description `drop_bps` is integer basis points -- 2500 is 25.00%.
         *
         *     `is_fresh` false means the listing has left our observation window or was
         *     seen gone; the UI must say so rather than link to a dead page.
         */
        PriceDrop: {
            /** Item Id */
            item_id: string;
            /** Title */
            title: string;
            /** Cover Url */
            cover_url: string | null;
            /** Then Cents */
            then_cents: number;
            /** Now Cents */
            now_cents: number;
            /** Drop Bps */
            drop_bps: number;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Is Fresh */
            is_fresh: boolean;
        };
        /** PriceDrops */
        PriceDrops: {
            /** Sample Size */
            sample_size: number;
            /** Data Days */
            data_days: number;
            /** Window Days */
            window_days: number;
            /** Rows */
            rows: components["schemas"]["PriceDrop"][];
        };
        /**
         * PricePoint
         * @description One observation. The series is ascending by time so a step chart can
         *     draw it directly: the price held until the next point, which is why the
         *     chart is a step line and never a smoothed curve.
         */
        PricePoint: {
            /** Price Cents */
            price_cents: number;
            /** Status */
            status: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Source */
            source: string;
            /** Want Count */
            want_count: number | null;
            /** View Count */
            view_count: number | null;
        };
        /**
         * PriceQuantiles
         * @description Empty below two samples: statistics.quantiles needs two data points,
         *     and a one-listing keyword is an ordinary day-one state here.
         */
        PriceQuantiles: {
            /** P10 */
            p10?: number | null;
            /** P25 */
            p25?: number | null;
            /** P50 */
            p50?: number | null;
            /** P75 */
            p75?: number | null;
            /** P90 */
            p90?: number | null;
        };
        /**
         * SessionState
         * @description Session health. Carries cookie NAMES and never values.
         */
        SessionState: {
            /** Origin */
            origin: string | null;
            /** Usable */
            usable: boolean;
            /** Needs Verification */
            needs_verification: boolean;
            /** Established At */
            established_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Challenged Apis */
            challenged_apis: string[];
            /** Cookie Names */
            cookie_names: string[];
            /** Proven */
            proven: boolean;
            /** Last Success At */
            last_success_at: string | null;
        };
        /**
         * SupplyDay
         * @description `collected` false means we have no record of a successful cycle that
         *     day, which is a different fact from `new_count == 0`. Rendering both as an
         *     empty bar is how a chart reports a dead market during downtime.
         */
        SupplyDay: {
            /** Date */
            date: string;
            /** New Count */
            new_count: number;
            /** Collected */
            collected: boolean;
            /** Runs Ok */
            runs_ok: number;
            /** Runs Failed */
            runs_failed: number;
        };
        /** SupplyTrend */
        SupplyTrend: {
            /** Sample Size */
            sample_size: number;
            /** Data Days */
            data_days: number;
            /** Window Days */
            window_days: number;
            /** Days */
            days: components["schemas"]["SupplyDay"][];
        };
        /** TestSendResult */
        TestSendResult: {
            /** Ok */
            ok: boolean;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WatchlistCreate
         * @description Two ways in: an item already in the database, or a pasted link.
         *
         *     The link path matters — without it the tool is closed inside its own search
         *     results, and the specific thing the user actually wants to buy (spotted in
         *     the app, or sent by a friend) cannot be watched at all.
         */
        WatchlistCreate: {
            /** Item Id */
            item_id?: string | null;
            /** Url */
            url?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Interval Seconds
             * @default 300
             */
            interval_seconds: number;
        };
        /** WatchlistPublic */
        WatchlistPublic: {
            /** Item Id */
            item_id: string;
            /** Title */
            title: string;
            /** Price Cents */
            price_cents: number;
            /** Added Price Cents */
            added_price_cents: number;
            /** Change Cents */
            change_cents: number;
            /** Change Ratio */
            change_ratio: number;
            /** Status */
            status: string;
            /** Cover Url */
            cover_url: string | null;
            /** Seller Nick */
            seller_nick: string;
            /** Seller Is Shop */
            seller_is_shop: boolean | null;
            /** Seller Credit Level */
            seller_credit_level: number | null;
            /** Seller Positive Rate */
            seller_positive_rate: number | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Listed Days */
            listed_days: number;
            /** Note */
            note: string | null;
            /** Price Watch Enabled */
            price_watch_enabled: boolean;
            /** Interval Seconds */
            interval_seconds: number;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Error */
            last_error: string | null;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /** WatchlistUpdate */
        WatchlistUpdate: {
            /** Note */
            note?: string | null;
            /** Price Watch Enabled */
            price_watch_enabled?: boolean | null;
            /** Interval Seconds */
            interval_seconds?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_monitors_api_monitors_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_monitor_api_monitors_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_monitor_api_monitors__monitor_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                monitor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_monitor_api_monitors__monitor_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                monitor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_monitor_api_monitors__monitor_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                monitor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitorPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_monitor_now_api_monitors__monitor_id__run_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                monitor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channels_api_channels_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_channel_api_channels_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_channel_api_channels__channel_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_channel_api_channels__channel_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_channel_api_channels__channel_id__test_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                channel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestSendResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notify_logs_api_notify_logs_get: {
        parameters: {
            query?: {
                limit?: number;
                channel_id?: number | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifyLogPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_api_watchlist_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_watchlist_api_watchlist_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_api_watchlist__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watchlist_api_watchlist__item_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_items_get: {
        parameters: {
            query?: {
                monitor_id?: number | null;
                min_price_cents?: number | null;
                max_price_cents?: number | null;
                status?: ("on_sale" | "sold" | "removed") | null;
                sort?: "-first_seen" | "first_seen" | "-last_seen" | "price" | "-price";
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_items__item_id__get: {
        parameters: {
            query?: {
                monitor_id?: number | null;
            };
            header?: {
                authorization?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_prices_api_items__item_id__prices_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_session_api_session_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_cookies_api_session_cookies_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CookieImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cookies_api_session_cookies_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    price_distribution_api_analytics_price_distribution_get: {
        parameters: {
            query: {
                keyword: string;
                days?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceDistribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    price_drops_api_analytics_price_drops_get: {
        parameters: {
            query: {
                keyword: string;
                days?: number;
                limit?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceDrops"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    supply_trend_api_analytics_supply_trend_get: {
        parameters: {
            query: {
                keyword: string;
                days?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplyTrend"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listing_duration_api_analytics_listing_duration_get: {
        parameters: {
            query: {
                keyword: string;
                days?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDuration"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_endpoints_api_llm_endpoints_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmEndpointPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_endpoint_api_llm_endpoints_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmEndpointCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmEndpointPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_endpoint_api_llm_endpoints__endpoint_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                endpoint_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_endpoint_api_llm_endpoints__endpoint_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                endpoint_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmEndpointUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmEndpointPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_endpoint_models_api_llm_endpoints__endpoint_id__models_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                endpoint_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmModelList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_endpoint_api_llm_endpoints__endpoint_id__test_post: {
        parameters: {
            query: {
                model: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                endpoint_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_scenario_api_llm_scenarios__scenario__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                scenario: "market" | "item";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmScenarioPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_scenario_api_llm_scenarios__scenario__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                scenario: "market" | "item";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmScenarioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmScenarioPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_default_prompt_api_llm_scenarios__scenario__default_prompt_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                scenario: "market" | "item";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmDefaultPrompt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_market_api_llm_analyze_market_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LlmMarketAnalyze"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmMarketAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_item_api_llm_analyze_item__item_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmItemAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    whoami_api_whoami_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
